spring:
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    修改为自己的服务器IP地址
    url: jdbc:mysql://bonfire_mysql:3306/star_project?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
    #    修改为自己的服务器的数据库的用户名
    username: root
    #    修改为自己的服务器的数据库的密码
    password: root
  session:
    timeout: 86400 # session失效时间 1 天
  servlet:
    multipart:
      max-file-size: 5MB # 单个文件大小 默认 1MB
      max-request-size: 50MB # 总文件大小  默认 10MB
  redis:
    port: 6379
    host: bonfire_redis
    database: 0
    password: root
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    locations: classpath:db/migration

server:
  port: 8088
  servlet:
    context-path: /api
upload-img:
  path: /app/images/ # 上传文件路径

logging:
  level:
    root: warn
    com.usercenter.controller: error
    sql: warn
    web: warn
mybatis-plus:
  global-config:
    banner: off
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

sa-token:
  is-print: off